### ISSUE TITLE
tracy debug bar?

### ISSUE THREAD

**Issue by landsman** [sunlight-cms/sunlight-cms-8#10]
What about replace Dev toolbar to Tracy Debug bar?
It know Ajax handling, customization by own panels etc?
We have it done with @jDanek for some older beta.

**Comment by jDanek** [comment]
Tracy is sure to add as a plugin, but if you want complete integration, you also have to replace ErrorHandler. I think so. https://github.com/sunlight-cms/sunlight-cms-8/blob/master/system/class/Core.php#L252

The custom devkit panels in this version of the system are of course also added.
https://github.com/sunlight-cms/sunlight-cms-8/blob/master/plugins/extend/devkit/Component/ToolbarRenderer.php#L71

**Comment by landsman** [comment]
I think that Tracy is better than Devkit and there is lots of plugins for it. 
Don't develop new wheel :-)

**Comment by ShiraNai7** [comment]
> @jDanek Tracy is sure to add as a plugin, but if you want complete integration, you also have to replace ErrorHandler. 

The error handler can be replaced at any time during the script's course so that's not an issue.

> I think that Tracy is better than Devkit and there is lots of plugins for it.
> Don't develop new wheel :-)

"Devkit" is a separate plugin that can also be disabled and/or replaced.

So it should be possible to integrate tracy through a plugin. There are no plans to put it in core.
