### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by landsman** [sunlight-cms/sunlight-cms-8#8]
- [ ] remove `keywords` field
- [x] go to `/install` if config.php missing and folder exist
   - [x] check vendor folder - alert if not exist

**Comment by ShiraNai7** [comment]
Added nicer error messages if _config.php_ or _vendor_ doesn't exist - no redirect.

**Comment by ShiraNai7** [comment]
After due consideration I've removed the keywords field from settings, pages and articles.
